import './structure.css'
export function crearEstructuraPpal() {
  let appInfo = document.querySelector('#app');
  const navGames = document.createElement("nav");
  appInfo.append(navGames);
  const titleNav = document.createElement("h1");
  navGames.append(titleNav);
  titleNav.innerText = "Games Hub";
  titleNav.id = "titleNav";
  const pNav = document.createElement("p");
  navGames.append(pNav);
  pNav.innerText = "Aquí están tus juegos favoritos, elige a cual quieres jugar.";
  const divNav = document.createElement("div");
  divNav.id = "divNav";
  navGames.append(divNav);
  let gamesInfo = ["tresEnRaya", "laOca", "memory"];
  gamesInfo.forEach(e => {
    const divGame = document.createElement("button");
    divGame.id = `${e}Select`;
    divGame.className = `buttonNavGames`;
    divNav.append(divGame);
    divGame.textContent = `${e}`
    const game = document.createElement("section");
    game.id = e;
    appInfo.appendChild(game);
    const title = document.createElement("h2");
    title.className = `gameTitle`;
    title.id = `${e}Title`;
    game.appendChild(title);
    const gameContainer = document.createElement("div");
    gameContainer.id = `${e}Container`;
    const gameTable = document.createElement("div");
    gameTable.id = `${e}Table`;
    const gamePlayers = document.createElement("div");
    gamePlayers.id = `${e}Players`;
    game.appendChild(gameContainer);
    gameContainer.appendChild(gameTable);
    gameContainer.appendChild(gamePlayers);
  });
  const tresEnRayaSelectGame = document.getElementById("tresEnRayaSelect");
  tresEnRayaSelectGame.innerText = "Jugar al tres en raya";
  const laOcaSelectGame = document.getElementById("laOcaSelect");
  laOcaSelectGame.innerText = "Jugar a la Oca";
  const memorySelectGame = document.getElementById("memorySelect");
  memorySelectGame.innerText = "Jugar al memory";
  const tresEnRayaTitleGame = document.getElementById("tresEnRayaTitle");
  tresEnRayaTitleGame.innerText = "JUGAR AL TRES EN RAYA";
  const laOcaTitle = document.getElementById("laOcaTitle");
  laOcaTitle.innerText = "JUGAR A LA OCA";
  const memoryTitle = document.getElementById("memoryTitle");
  memoryTitle.innerText = "JUGAR AL MEMORY";
};